server:
  port: 8090
  servlet:
    context-path: /api/v1
spring:
  application:
    name: firstEntity
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: haythem
    url: jdbc:postgresql://localhost:5432/projectentities
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
